blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

app_name="blog"
urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name="index"),
    url(r'^post/(?P<pk>[0-9]+)/$',views.PostDetailView.as_view(),name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.ArchivesView.as_view(),name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$',views.CategoryView.as_view(),name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^tags/$', views.AlltagView.as_view(), name='tags'),
    url(r'^all/$', views.AllpostView.as_view(), name='all'),
    url(r'^search/$', views.search, name='search'),


]

comments/urls.py
from django.conf.urls import url,include
from . import views

app_name="comments"
urlpatterns = [
    url(r'^(?P<post_pk>[0-9]+)/$',views.do_comment,name='do_comment'),

]

rblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^comment/', include('comments.urls')),
    url(r'',include('blog.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import strip_tags
import markdown
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=100)
    def __str__(self):
        return self.name
class Tag(models.Model):
    name=models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Post(models.Model):
    title=models.CharField(max_length=70)
    body=models.TextField()
    create_time=models.DateTimeField()
    modified_time=models.DateTimeField()
    excerpt=models.CharField(max_length=200,blank=True)
    category=models.ForeignKey(Category)
    tags=models.ManyToManyField(Tag)
    author=models.ForeignKey(User)
    views=models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})
    def increase(self):
        self.views+=1
        self.save(update_fields=["views"])
    def get_markdown(self):
        return markdown.markdown(self.body, extensions=["markdown.extensions.extra", "markdown.extensions.codehilite",
                                                 "markdown.extensions.toc", ])
    class Meta:
        ordering=["-create_time"]
    def save(self,*args,**kwargs): #重写sava方法，保存数据时会优先调用该方法。
        if not self.excerpt:
            self.excerpt=strip_tags(self.get_markdown())[:100]
        super(Post, self).save(*args,**kwargs)  #调用父类方法

comments/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.db import models

class Comment(models.Model):
    name=models.CharField(max_length=50)
    email=models.EmailField(max_length=50)
    url=models.URLField(blank=True)
    text=models.TextField()
    create_time=models.DateTimeField(auto_now_add=True)
    post=models.ForeignKey("blog.post")
    def __str__(self):
        return self.text[:20]

comments/forms.py
#coding:utf-8

from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:#内部类
        model=Comment
        fields=["name","text","url","email"]  #指明需要显示的字段

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render,get_object_or_404
from models import *
import markdown
from comments.forms import CommentForm
from django.views.generic import ListView,DetailView,DayArchiveView


class IndexView(ListView):
    model = Post
    template_name = "blog/index.html"
    context_object_name = "post_list"
    paginate_by = 5
    def get_context_data(self, **kwargs):
        context=super(IndexView, self).get_context_data(**kwargs)
        paginator=context.get("paginator")
        page=context.get('page_obj')
        is_paginated=context.get("is_paginated")
        pagination_data=self.get_pagination_data(paginator,page,is_paginated)
        context.update({"page_range":pagination_data})
        return context
    def get_pagination_data(self,paginator,page,is_paginated):  #处理页码数据，将附近页码显示，较远省略，首尾显示。
        if not is_paginated:
            return {}
        page_num=page.number
        total_page=paginator.num_pages
        page_range=list(paginator.page_range)
        if page_num-3>0:
            page_range[1:page_num-3]=["." for i in range(1,page_num-3)]
        if page_num+3<total_page:
            page_range[page_num+2:total_page-1]=["." for i in range(page_num+2,total_page-1)]
        return page_range

class PostDetailView(DetailView):
    model = Post
    template_name = "blog/detail.html"
    context_object_name = "post"
    def get(self, request, *args, **kwargs):
        response=super(PostDetailView, self).get(request,*args,**kwargs)   #调用父类get方法后，才会有object实例，其值即为单个的post
        self.object.increase()
        return response
    def get_object(self, queryset=None):   #该方法在get中被调用，用于获取对象实例
        post=super(PostDetailView, self).get_object(queryset=None)
        post.body=post.get_markdown()
        return post
    def get_context_data(self, **kwargs):   #装配需要的模板变量值
        context=super(PostDetailView, self).get_context_data(**kwargs)   #将post对象和其键名匹配起来加入字典
        form=CommentForm()
        comment_list=self.object.comment_set.all()
        context.update({"form":form,"comment_list":comment_list})
        return context

class ArchivesView(ListView):
    model = Post
    template_name = "blog/archive.html"
    context_object_name = "post_list"
    def get_queryset(self):
        year=self.kwargs.get("year")
        month=self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(create_time__year=year,create_time__month=month)


class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get("pk"))
        return super(CategoryView, self).get_queryset().filter(category=cate)

class TagView(IndexView):
    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get("pk"))
        return super(TagView, self).get_queryset().filter(tags=tag)


class AlltagView(IndexView):
    model = Post
    template_name = "blog/tag.html"
    context_object_name = "post_list"
    paginate_by = 5

class AllpostView(ListView):
    model = Post
    template_name = "blog/archive.html"
    context_object_name = "post_list"


def search(request):
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = '请输入关键词'
        return render(request, 'blog/index.html', {'error_msg': error_msg})

    post_list = Post.objects.filter(title__icontains=q)
    return render(request, 'blog/index.html', {'error_msg': error_msg,
                                               'post_list': post_list})

comments/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render,get_object_or_404,redirect
from .forms import CommentForm
from .models import Comment
from blog.models import Post

def do_comment(request,post_pk):
    post=get_object_or_404(Post,pk=post_pk)
    if request.method=="POST":
        form=CommentForm(request.POST)    #构造表单实例
        if form.is_valid():
            comment=form.save(commit=False)  #生成数据库模型实例，但是不保存数据到数据库
            comment.post=post
            comment.save()#提交数据到数据库
            return redirect(post)
        else:
            comment_list=post.comment_set.all()
            context={
                "form":form,
                "post":post,
                "comment_list":comment_list
            }
            return  render(request,"blog/detail.html",context=context)
    else:
        return redirect(post)

templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    {% load blog_tags %}


<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta http-equiv="Cache-Control" content="no-siteapp">
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=1, minimum-scale=1, maximum-scale=1">
<meta name="renderer" content="webkit">
<meta name="google" value="notranslate">
<meta name="robots" content="index,follow">



<link rel="stylesheet" href="{% static 'blog/css/index.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">


        <meta name="keywords" content="简单，美好，Pyhton">
        <meta name="description" content="简单，美好，Pyhton">
        {% block title%}
        <title>Forin · 博客笔记</title>
        {% endblock title %}
    </head>
    <body>
        <article class="container">
            <header class="header-wrap">
  <a class="index" href="/">
    <img class="logo" src="{% static 'blog/img/avatar.jpg' %}" />
    Forin · 博客笔记
  </a>
  <ul class="menu">
      <li class="menu-item"><a href="{% url 'blog:all' %}">归档</a></li>
      <li class="menu-item"><a href="{% url 'blog:tags' %}">标签</a></li>

  </ul>
</header>

            <article class="main page">
                <header class="header site">

                        <img class="logo" src="{% static 'blog/img/avatar.jpg' %}" />
                        <h1 class="title">Forin · 博客笔记</h1>
                        <h2 class="subtitle">简单，美好，Pyhton</h2>
                        <div class="search-wrap">

      <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
      {% csrf_token %}
      <input id="search" class="search" name="q" placeholder="Search" required>
      <button type="submit" class="logo" ><span class="ion-ios-search-strong"></span> 立即搜索 </button>
    </form>

  <svg class="icon" width="25" height="25" viewBox="0 0 25 25"><path d="M20.067 18.933l-4.157-4.157a6 6 0 1 0-.884.884l4.157 4.157a.624.624 0 1 0 .884-.884zM6.5 11c0-2.62 2.13-4.75 4.75-4.75S16 8.38 16 11s-2.13 4.75-4.75 4.75S6.5 13.62 6.5 11z"></path></svg>
</div>
                {% block top %}
                {% endblock top %}

                </header>

                {% block main %}
                {% endblock main %}


                <!--<section class="">-->

                    <!--<span class="nav">1 / 2</span>-->
                    <!--<a class="next" href="/blog/page2.html">下一页</a>-->
                <!--</section>-->
            <!--</article>-->
        <!--</article>-->




         {% block footer%}
         {%endblock footer%}

templates/blog/archive.html
{% extends 'base.html'%}
{% block title %}
<title>归档-所有文章-Forin·博客笔记</title>
{% endblock title %}

{% block main %}
{% load blog_tags %}

                  <div class="widget widget-archives">
                    <h3 class="widget-title">归档-所有文章</h3>
                    {% get_all_posts as post_list %}

                <ul class="archive-list">
                     {% for post in post_list %}

                            <li class="article-item">
                                <span class="date">{{ post.create_time }}</span>
                                <a  class="preview content" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </li>

                    {% empty %}
                    暂无归档
                    {% endfor %}
                    
                </ul>
{% endblock main %}

templates/blog/detail.html
{% extends 'base.html' %}
{% block title %}
<title>{{ post.title }}-Forin·博客笔记</title>
{% endblock title%}

{% block main %}
    {% load blog_tags %}

        <meta name="keywords" content="{{ post.tags}}">
        <meta name="description" content="{{ post.title}}">
        <meta name="author" content="{{post.author}}">
        <title>{{ post.title}}</title>
    </head>
    <body>
        <article class="container">
            <header class="header-wrap">
</header>

            <article class="main article">
                <h1 class="title">{{ post.title}}</h1>
                <section class="info">
                    <a class="name" href="/">{{post.author}}</a>
                    
                    <span class="date" data-time="{{ post.create_time}}"><span class="from">{{ post.create_time}}</span></span>
                    
                    {% for tag in post.tags.all %}
                    <a class="tag" href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                     {% endfor %}
                <article class="content">{{ post.body | safe}}
</article>
                <section class="author">
                    <a class="name" href="/">{{post.author}}</a>
                    <div class="intro">Python死忠粉-敲Python代码就像在沐浴阳光</div>
                </section>
                <section class="recommend">
                    

                    </section>


         <h5 >随机推荐的博文</h5>
                    {% get_recent_posts as post_list %}

                    <ul>
                                {% for post in post_list %}
                        <li>
                            <a class="preview content" href="{{ post.get_absolute_url }}">{{ post.title}}</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="from">{{post.create_time}}</span>
                        </li>
                        {% empty%}
                         <li>
                          暂时没有新文章
                        </li>
                        {% endfor %}
                    </ul>

                    
                </section>


                 <section class="comment-area " id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:do_comment' post.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label>名字：{{form.name}}{{form.name.errors }}</label>
                            </div>
                            <div class="col-md-4">
                                <label >邮箱：{{ form.email}} {{ form.email.errors }}</label>
                            </div>
                            <div class="col-md-4">
                                <label >网址：{{form.url}} {{ form.url.errors }}</label><span>（请以http://开头）</span>
                            </div>
                            <div class="col-md-12">
                                <label >评论：{{form.text}} {{ form.text.errors }}</label>
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ post.comment_set.count}}</span> 条评论</h3>
                        <ul class="preview content">
                            {% for comment in comment_list %}
                            <li class="">
                                <span class="nickname">{{comment.name}}</span>
                                <time class="submit-date" datetime="{{comment.create_time}}">{{comment.create_time}}</time>
                                <div class="text">
                                  {{comment.text}}
                                </div>
                            </li>
                            {%empty%}
                            暂时没有评论
                            {% endfor%}
                        </ul>
                    </div>
                </section>
                



            </article>
        </article>



{% endblock main%}

templates/blog/index.html
{% extends 'base.html' %}
{% block main %}


  <ul class="article-list">
                     {% for post in post_list%}
                    <li class="article">
                        <a class="title" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        <section class="preview content"><p>{{ post.excerpt }}</section>
                        <section class="info">
                            <a class="name" href="/">{{ post.author }}</a>

                            <span class="date" data-time="{{ post.create_time }}" ><span class="from"> {{ post.create_time}} </span></span>

                            <span class="tags">
                            {% for tag in post.tags.all %}
                            <a class="tag" href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                             {% endfor %}
                            </span>
                        </section>
                    </li>
                  {% empty %}
                 <h1>暂时没有文章</h1>
                {% endfor %}

                </ul>


                 {% if is_paginated %}

                 <div class="page-nav preview content" font-size="30px">
                     页码：
                    {% for page in page_range %}

                     {% if page == page_obj.number %}
                     <span class="current" style="color: #FF0000">{{ page_obj.number }}</span>
                     {% elif page == "." %}
                     <span>{{ page }}</span>
                     {% else %}
                     <a href="?page={{ page }}">{{ page }}</a>
                     {% endif %}
                {%endfor%}
                </div>
                {% endif %}




       {% endblock main%}

templates/blog/tag.html
{% extends "base.html" %}

{% block title %}
<title>所有标签-Forin·博客笔记</title>
{% endblock title %}

{% block main %}
{% load blog_tags %}

            <article class="main tag">
                <header class="header">
                    <span class="title">标签</span>
                </header>
                <ul class="tag-list">

                    {% get_tags as tags %}
                     {% for tag in tags %}
                    <li class="tag-item">
                        <a class="tag-name" href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}<span class="tag-count"></span></a>
                    </li>

                    {% endfor %}

                </ul>
            </article>
        </article>
  {% endblock main %}